# Generated by Django 3.2.8 on 2021-11-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20211102_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email_copies',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email_message',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='form',
            name='send_email',
        ),
    ]
