# Generated by Django 3.2.8 on 2021-11-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20211102_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='form',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='form',
            name='response',
        ),
    ]
