# Generated by Django 3.2.8 on 2021-11-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20211102_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='form',
            name='response',
        ),
    ]
