# Generated by Django 3.2.8 on 2021-11-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20211102_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='sites',
        ),
    ]
